version: '3.7'

services:
  mdetr_ore:
    image: mmaaz60/mdetr:v1.0
    volumes:
      - ./pretrain.sh:/workspace/pretrain.sh
      - ./data:/workspace/data
      - ./results:/workspace/results
    container_name: mdetr_ore
    command: /bin/bash -c "bash pretrain.sh"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    shm_size: '32gb'